package com.team5.projrental.common.exception;

import lombok.Getter;

@Getter
public enum ErrorStatus {
    ILLEGAL_EX_MESSAGE(4099),
    ILLEGAL_PRODUCT_PICS_EX_MESSAGE(4098),
    ILLEGAL_CATEGORY_EX_MESSAGE(4097),
    ILLEGAL_PAYMENT_EX_MESSAGE(4096),
    ILLEGAL_STATUS_EX_MESSAGE(4095),
    ILLEGAL_RANGE_EX_MESSAGE(4094),
    ILLEGAL_DATE_EX_MESSAGE(4093),
    //
    BUY_DATE_MUST_BE_LATER_THAN_TODAY_EX_MESSAGE(4199),
    RENTAL_DATE_MUST_BE_BEFORE_THAN_TODAY_EX_MESSAGE(4198),
    RENTAL_END_DATE_MUST_BE_AFTER_THAN_RENTAL_START_DATE_EX_MESSAGE(4197),
    CAN_NOT_BLANK_EX_MESSAGE(4196),
    AUTHENTICATION_FAIL_EX_MESSAGE(4195),
    CAN_NOT_DEL_USER_EX_MESSAGE(4194),
    REVIEW_ALREADY_EXISTS_EX_MESSAGE(4193),
    //
    NO_SUCH_USER_EX_MESSAGE(4299),
    NO_SUCH_PRODUCT_EX_MESSAGE(4298),
    NO_SUCH_PAYMENT_EX_MESSAGE(4297),
    NO_SUCH_PASSWORD_EX_MESSAGE(4296),
    NO_SUCH_ID_EX_MESSAGE(4295),
    NO_SUCH_REVIEW_EX_MESSAGE(4294),
    //
    BAD_ADDRESS_INFO_EX_MESSAGE(4399),
    BAD_INFO_EX_MESSAGE(4398),
    BAD_SORT_EX_MESSAGE(4397),
    BAD_RENTAL_DEL_EX_MESSAGE(4396),
    BAD_RENTAL_CANCEL_EX_MESSAGE(4395),
    BAD_DIV_INFO_EX_MESSAGE(4394),
    BAD_PIC_EX_MESSAGE(4393),
    BAD_ID_EX_MESSAGE(4392),
    BAD_PRODUCT_INFO_EX_MESSAGE(4391),
    BAD_TYPE_EX_MESSAGE(4390),
    BAD_WORD_EX_MESSAGE(4389),


    //
    ALL_INFO_NOT_EXISTS_EX_MESSAGE(4499),
    //
    SERVER_ERR_MESSAGE(5000);


    private int code;

    ErrorStatus(int code) {
        this.code = code;
    }

}
